[build]
  publish = "frontend/dist"   # Path to the directory containing your built assets
  command = "npm run build"   # Command to build your site, adjust if needed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
